### ISSUE TITLE
Print in Chromium mit schwarzem Hintergrund

### ISSUE THREAD

**Issue by nerdoc** [medworx/kindisch#129]
Bin grad auf was lustiges gestoßen. Wenn man im Chromium auf die Druck-Seite geht und dann die Druckvorschau ansieht, schauts so aus:
![bildschirmfoto von 2014-10-30 21 51 11](https://cloud.githubusercontent.com/assets/2955584/4850919/4b6498bc-606e-11e4-8354-17bab48073f0.png)
Janne, kannst des vielleicht mal in Windows prüfen - oder ist das nur in Linux (Chromium 33)?

Eventuell ist das ein Bug in Chromium: https://code.google.com/p/chromium/issues/detail?id=226137

**Comment by drfoehn** [comment]
War ein Fehler in der print.css
