### ISSUE TITLE
Auto Assign des Avatars funktioniert nicht

### ISSUE THREAD

**Issue by nerdoc** [medworx/kindisch#153]
- Auto Assign des Avatars (http://kindisch.at/admin/config/people/avatar_selection) für neu registrierte Nutzer funktioniert nicht - https://www.drupal.org/node/734116

**Comment by drfoehn** [comment]
der pfad war falsch eingestellt in http://kindisch.at/admin/config/people/accounts.
Standardbild liegt in sites/default/files/user_pictures/schmetterling_rot.png

**Comment by nerdoc** [comment]
evtl könnten wir das noch default.jpg nennen?
Ich weiß, nerdig. Aber FürSpäterMal™.
