### ISSUE TITLE
In der Tablet Landscape ist die Userleiste nicht sichtbar

### ISSUE THREAD

**Issue by drfoehn** [medworx/kindisch#182]
Im Portrait kommt der Balken zum rausfahren (muesste auch nicht sein) aber im Landscape Modus kommt man nirgends zum Usermenue

**Comment by nerdoc** [comment]
Ja ich glaub das ist das selbe Problem wie auf dem Asuspad Transformer. Per CSS Media Query wird "Desktop" erkannt, daher wird die Leiste rechts ausgeblendet. Per  PHP/BrowseCap-Modul wird mobile erkannt, daher wird das Usermenu in die Seitenleiste verschoben - die ausgeblendet ist.

**Comment by nerdoc** [comment]
gefixt. per $is_mobile wird das mobile menu per PHP nun gar nicht angezeigt, und sonst immer.
Keine Ausblendung mehr per CSS.
