### ISSUE TITLE
Slogan erweitern

### ISSUE THREAD

**Issue by drfoehn** [medworx/kindisch#187]
Von Eltern für Eltern
in einer zweiten Zeile

**Comment by drfoehn** [comment]
Hab mal auf Testing die page.tpl.php und die global-styles entsrechend verändert.

Was sagst?

**Comment by nerdoc** [comment]
ja ist gut prinzipiell. Aber ich bin echt gegen das "&lt;br&gt;". Das bedingt z.B. dass man das span tag nicht mehr z.B. rechtsbündig, alsu unabhängig von "Salzburger Kinder-Freizeit-Netzwerk" CSSen kann.
Also ich mach das mal als div ohne br.

**Comment by drfoehn** [comment]
Ja passt super. Danke.

**Comment by nerdoc** [comment]
So. jetzt kannst z.b. einfügen:
```
.slogan_eltern {
  text-align: center;
}
```

**Comment by drfoehn** [comment]
is drin
